-- AlterTable: add ACCEPTED / DECLINED to the OrderStatus enum columns
ALTER TABLE `orders` MODIFY `status` ENUM('PENDING_PAYMENT', 'PAID', 'ACCEPTED', 'DECLINED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'PAUSED', 'CANCELLED') NOT NULL DEFAULT 'PENDING_PAYMENT';
ALTER TABLE `package_delivery_days` MODIFY `status` ENUM('PENDING_PAYMENT', 'PAID', 'ACCEPTED', 'DECLINED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'PAUSED', 'CANCELLED') NOT NULL DEFAULT 'PREPARING';
